defaults:
  - dataset: gtsrb   
  - transforms: base_transform
  - dataloader: gtsrb_dataloader
  - train: train
  - model: light_model
  - load_dataset: gtsrb
  - metrics: base_classification_metrics
  - optimizer: adamw
# batch_size: 64
# epochs: 20
# lr: 0.001
